---
title: "Pipeline References"
author: "EP"
date: "2026-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pipeline References 

List of references for the packages used in this pipeline.

targets
"readr", "sf", "dplyr", "terra", "tidyr", "tidyverse", "vegan", 
"ggplot2", "MASS", "betareg", "ranger"

Author surname, initials or Organisation (Year of publication or last update) Title of Website. 
Available from: URL [Accessed DD Month YYYY]. 

- Landau, W. The Comprehensive R Archive Network (2026) targets: Dynamic Function-Oriented 'Make'-Like Declarative Pipelines. Available from: https://cran.r-project.org/web/packages/targets/index.html [Accessed 04/08/2026]
- Wickham, H., Hester, J., Francois, R., Bryan, J. et al. The Comprehensive R Archive Network (2026) readr: Read Rectangular Text Data. Available from: https://cran.r-project.org/web/packages/readr/index.html [Accessed 04/08/2026]
- Pebesma, E., Bivand, R., Racine, E., Sumner, M. et al. The Comprehensive R Archive Network (2026) sf: Simple Features for R. Available from: https://cran.r-project.org/web/packages/sf/index.html [Accessed 04/08/2026]
- Wickham, H., Francois, R., Henry, L., Muller, K., et al. The Comprehensive R Archive Network (2026) dplyr: A Grammar of Data Manipulation. Available from: https://cran.r-project.org/web/packages/dplyr/index.html [Accessed 04/08/2026]
- Hijmans, R., Brown, A., Barbosa, M., Dyba, K. et al. The Comprehensive R Archive Network (2026) terra: Spatial Data Analysis. Available from: https://cran.r-project.org/web/packages/terra/index.html [Accessed 04/08/2026]
- Wickham, H, Vaughan. D., Girlich, M., Ushey, K et al. The Comprehensive R Archive Network (2025) tidyr: Tidy Messy Data. Available from:  https://cran.r-project.org/web/packages/tidyr/index.html [Accessed: 04/08/2026]
- Wickham, H. The Comprehensive R Archive Network (2023) tidyverse: Easily Install and Load the `Tidyverse`. Available from: https://cran.r-project.org/web/packages/tidyverse/index.html [Accessed: 04/08/2026]
- Oksanen, J., Simpson, G., Blanchet F.G., Kindt, R., et al. The Comprehensive R Archive Network (2026) vegan: Community Ecology Package. Available from: https://cran.r-project.org/web/packages/vegan/index.html [Accessed 04/08/2026]
- Wickham, H., Chang, W. Henry, L., Lin Pedersen, T. et al. The Comprehensive R Archive Network (2026) ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics. Available from: https://cran.r-project.org/web/packages/ggplot2/index.html [Accessed 04/08/2026]
- Ripley, B., Venables, B., Bates, D.M., Hornik, K. et al. The Comprehensive R Archive Network (2026) MASS: Support Functions and Datasets for Venables and Ripley's MASS. Available from: https://cran.r-project.org/web/packages/MASS/index.html [Accessed: 04/08/2026]
- Zeileis, A., Cribari-Neto, F., Grun, B., Kosmidis, I. et al. The Comprehensive R Archive Network (2026) betareg: Beta Regression. Available from:https://cran.r-project.org/web/packages/betareg/index.html [Accessed 04/08/2026] 
- Wright, M.N., Wager, S., and Probst, P. The Comprehensive R Archive Network (2026) ranger: A Fast Implementation of Random Forests. Available from: https://cran.r-project.org/web/packages/ranger/index.html [Accessed: 04/08/2026]
